version: "3.8"  # Docker Compose 파일 버전을 지정합니다. "3.8"은 사용 가능한 최신 버전 중 하나입니다.

services:
  master1:
    build: 
      context: .
      dockerfile: hd-base.Dockerfile
    container_name: master1
    hostname: master1
    ports:
      - "9870:9870"    # NameNode Web UI
      - "8088:8088"    # ResourceManager Web UI
      - "19888:19888"   # MapReduce JobHistory Server Web UI
    volumes:
      - shared_keys:/shared_keys
      - ./master/hdfs-site.xml:/usr/local/bin/master/hdfs-site.xml
      - ./master/setup-master-hadoop-env.sh:/usr/local/bin/master/setup-master-hadoop-env.sh
    networks:
      nowdoboss_net:  # 사용할 네트워크를 지정합니다.
        ipv4_address: 172.24.0.100
    command: >
      /bin/bash -c "
      /usr/local/bin/setup-hadoop.sh &&
      /usr/local/bin/update-hosts.sh &&
      /usr/local/bin/init-ssh-keys.sh &&
      /usr/local/bin/collect-ssh-keys.sh 3 &&
      /usr/local/bin/master/setup-master-hadoop-env.sh
      "

  worker1:
    build: 
      context: .
      dockerfile: hd-base.Dockerfile
    container_name: worker1
    hostname: worker1
    volumes:
      - shared_keys:/shared_keys
      - ./worker/hdfs-site.xml:/usr/local/bin/worker/hdfs-site.xml
      - ./worker/setup-worker-hadoop-env.sh:/usr/local/bin/worker/setup-worker-hadoop-env.sh
    networks:
      nowdoboss_net:  # 사용할 네트워크를 지정합니다.
        ipv4_address: 172.24.0.101
    command: >
      /bin/bash -c "
      /usr/local/bin/setup-hadoop.sh &&
      /usr/local/bin/update-hosts.sh &&
      /usr/local/bin/init-ssh-keys.sh &&
      /usr/local/bin/collect-ssh-keys.sh 5 &&
      /usr/local/bin/worker/setup-worker-hadoop-env.sh
      "

  worker2:
    build: 
      context: .
      dockerfile: hd-base.Dockerfile
    container_name: worker2
    hostname: worker2
    volumes:
      - shared_keys:/shared_keys
      - ./worker/hdfs-site.xml:/usr/local/bin/worker/hdfs-site.xml
      - ./worker/setup-worker-hadoop-env.sh:/usr/local/bin/worker/setup-worker-hadoop-env.sh
    networks:
      nowdoboss_net:  # 사용할 네트워크를 지정합니다.
        ipv4_address: 172.24.0.102
    command: >
      /bin/bash -c "
      /usr/local/bin/setup-hadoop.sh &&
      /usr/local/bin/update-hosts.sh &&
      /usr/local/bin/init-ssh-keys.sh &&
      /usr/local/bin/collect-ssh-keys.sh 7 &&
      /usr/local/bin/worker/setup-worker-hadoop-env.sh
      "

networks:
  nowdoboss_net:  # 사용할 네트워크를 정의합니다.
    name: nowdoboss_net
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16

volumes:
  shared_keys: